[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://host.docker.internal:4723"
status-endpoint = "/status"

[[relay.configs]]
max-sessions = 1
stereotype = '{"platformName":"android","appium:automationName":"UIAutomator2","appium:udid":"emulator-5554","appium:platformVersion":"12","appium:systemPort":"8101"}'
